name: flygym
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch-lightning
  - lightning
  - pytorch_geometric
  - rich
  - stable-baselines3
  - seaborn
  - tensorboard
  - tensorboardx
  - pandas
